- name: Creation des utilisateurs
  hosts: all
  become: yes
  roles:
    - createuser
    
- name: Installation du serveur web
  become_user: app-salaire
  hosts: [ServeursWEB]
  roles:
    - SQLWeb
    
- name: Installation de mariadb
  become_user: app-salaire
  hosts: [db]
  roles:
    - bdd
